version: '3.8'

services:
  # Production service
  dewu-mock-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - CONFIG_PROFILE=production
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development service
  dewu-mock-api-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - CONFIG_PROFILE=development
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    profiles:
      - dev

  # Testing service
  dewu-mock-api-test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=testing
      - CONFIG_PROFILE=testing
    volumes:
      - .:/app
      - /app/node_modules
    command: npm test
    profiles:
      - test